input = '''ACGGGGTCTCGAAAAAAGGAGAATGGGATGAGAAGGATATATGGGTAGTGTCATTTTTTAACTTGCAGAT
TTCATCCTAGTCTTCCAGTTATCGTTTCCTAGCACTCCATGTTCCCAAGATAGTGTCACCACCCCAAGGA
CTCTCTCTCATTTTCTTTGCCTGGGCCCTCTTTCTACTGAGGAGTCGTGGCCTTCCATCAGTAGAAGCCG
GATGTTCTTGTGTCCGAAATTGGTGGGTTCTTGGTCTCACTGACTTCAAGAATGAAGTTGCGGACCCTCA
CGGTGAGTGGTACAGTTCTTAAAGATGATGTGTCCAGAGTTTGTTCCTTCTGATGTTCGGACGTGTTCAG
AGTTACCTCCTTCTGGTGGATTCGTGGTCTCGCTGGCTTCAGGAGTGAAGCTGCAGACCTTTGCGGTGAG
TGTTACAGCTCTTAAGGCGGCATGTCTGGAGTTTGTTCGTTCCTCCCGTCTGGAGTTGTTCATTCCTCCT
GGTGGGTTCGTGGTCTCGCTGGCTTCAGGAGTGAAGCTGCAGACCTCTGCGGTCGGTGTTACCAGCAGAT
AAATGCTATGCGGACCCAAAGAGTGAGCAGCAGCAAGATTTATTGCAAAGAGCACAAGAACAAAGCTTCC
ACAGCGTGGAAGGAGACCAGAGCGGGTTGCTGCTGCTGGCTCAGGCAGCCTGCATTTTTTTTTTTTTTTT
TTTTTTTTTTTGAGATGGAGTCTCCCTCTGTCACCCAGGCTGGAATGCAGTGGTGCAATCTGGGCTCACT
GCAAGCTCCGCCTCCCGGGTTCACGCCATTCTCCTGCCTCAACCTCCCCAGTAGAGGGGATTACAGGCAC
CCACCACCGCACCCAGCTAATATTTTGTCTTTTTAGTAGAGTCGGGGTTTCACTGTGTTAGCCAGGATGG
TCTCGATCTCTTGACCTCGTGATCCACCCCTCTAGGCCTCCCAAATTGCTGGGATTACAGGTGTGAGCCA'''

print input

a=0.00 ;t=0.00 ;c=0.00 ;g=0.00



for line in input:
    for ch in line:
        if ch =="A":
            a+=1
        elif ch =="T":
            t+=1
        elif ch =="C":
            c+=1
        elif ch =="G":
            g+=1
            
print "A = %.1f, T = %.1f, C = %.1f, G = %.1f " %(a,t,c,g)

sum = a+t+c+g
print "sumation = %d" % (sum)
ra=a/sum
rt=t/sum
rc=c/sum
rg=g/sum
print "ratio A = %.2f \nratio T = %.2f \nratio C = %.2f \nratio G = %.2f\n" %(ra,rt,rc,rg)         